import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@prisma/client";

const connectionString = process.env.DATABASE_URL!;
const adapter = new PrismaPg({ connectionString });
const db = new PrismaClient({ adapter });

async function main() {
  await db.product.deleteMany();

  await db.product.createMany({
    data: [
      {
        name: "Ashwagandha KSM-66",
        slug: "ashwagandha-ksm-66",
        brand: "Himalaya Wellness",
        description: "600mg organic root extract. Reduces cortisol and supports deep sleep.",
        price: 24.95,
        category: "supplements",
        certifications: ["USDA Organic", "Non-GMO", "Vegan"],
        imageUrl: "https://images.unsplash.com/photo-1611241893603-3c359704e0ee?w=400&q=80",
      },
      {
        name: "Magnesium Glycinate 400mg",
        slug: "magnesium-glycinate",
        brand: "Pure Encapsulations",
        description: "Most bioavailable magnesium form. Supports sleep and stress relief.",
        price: 32.50,
        category: "supplements",
        certifications: ["Non-GMO", "Vegan", "GMP Certified"],
        imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80",
      },
      {
        name: "Rhodiola Rosea 500mg",
        slug: "rhodiola-rosea",
        brand: "Gaia Herbs",
        description: "Adaptogenic herb that combats fatigue and sharpens focus without caffeine.",
        price: 21.00,
        category: "supplements",
        certifications: ["Organic", "Vegan"],
        imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&q=80",
      },
      {
        name: "Elderberry + Zinc Complex",
        slug: "elderberry-zinc",
        brand: "Garden of Life",
        description: "Immune defense with elderberry and zinc for seasonal protection.",
        price: 19.95,
        category: "supplements",
        certifications: ["USDA Organic", "Non-GMO", "Vegan"],
        imageUrl: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=400&q=80",
      },
      {
        name: "Turmeric Curcumin C3",
        slug: "turmeric-curcumin",
        brand: "Thorne Research",
        description: "Anti-inflammatory with BioPerine for enhanced absorption.",
        price: 19.95,
        category: "supplements",
        certifications: ["Non-GMO", "GMP Certified"],
        imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80",
      },
      {
        name: "Lavender Essential Oil",
        slug: "lavender-essential-oil",
        brand: "Plant Therapy",
        description: "100% pure therapeutic grade lavender for aromatherapy and relaxation.",
        price: 12.00,
        category: "essential-oils",
        certifications: ["USDA Organic", "Non-GMO"],
        imageUrl: "https://images.unsplash.com/photo-1528720208104-3d9bd03cc9d4?w=400&q=80",
      },
      {
        name: "Lion's Mane Mushroom",
        slug: "lions-mane-mushroom",
        brand: "Host Defense",
        description: "Organic lion's mane mushroom for cognitive function, memory, and nerve support.",
        price: 29.95,
        category: "supplements",
        certifications: ["USDA Organic", "Non-GMO", "Vegan", "Gluten-free"],
        imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&q=80",
      },
      {
        name: "Vitamin D3 + K2",
        slug: "vitamin-d3-k2",
        brand: "Jarrow Formulas",
        description: "5000 IU D3 paired with K2 for optimal calcium absorption and immune support.",
        price: 18.50,
        category: "supplements",
        certifications: ["Non-GMO", "Vegan", "GMP Certified"],
        imageUrl: "https://images.unsplash.com/photo-1550572017-edd951b55104?w=400&q=80",
      },
      {
        name: "Collagen Peptides Powder",
        slug: "collagen-peptides",
        brand: "Vital Proteins",
        description: "Grass-fed collagen for skin elasticity, joint health, and gut support.",
        price: 34.99,
        category: "supplements",
        certifications: ["Non-GMO", "GMP Certified", "Third-party tested"],
        imageUrl: "https://images.unsplash.com/photo-1612540139150-4b55a2b3cb44?w=400&q=80",
      },
      {
        name: "Probiotics 50 Billion CFU",
        slug: "probiotics-50-billion",
        brand: "Garden of Life",
        description: "50 billion CFU with 16 probiotic strains for gut health and immunity.",
        price: 39.99,
        category: "supplements",
        certifications: ["USDA Organic", "Non-GMO", "Vegan", "Gluten-free"],
        imageUrl: "https://images.unsplash.com/photo-1576086213369-97a306d36557?w=400&q=80",
      },
      {
        name: "Melatonin 3mg Gummies",
        slug: "melatonin-gummies",
        brand: "Natrol",
        description: "Drug-free sleep aid gummies. Fall asleep faster, stay asleep longer.",
        price: 12.99,
        category: "supplements",
        certifications: ["Non-GMO", "Vegan", "Gluten-free"],
        imageUrl: "https://images.unsplash.com/photo-1559181567-c3190b2e6af9?w=400&q=80",
      },
      {
        name: "Omega-3 Fish Oil 2000mg",
        slug: "omega-3-fish-oil",
        brand: "Nordic Naturals",
        description: "High-potency omega-3 for heart, brain, and joint health. Burpless formula.",
        price: 28.95,
        category: "supplements",
        certifications: ["Non-GMO", "Third-party tested", "GMP Certified"],
        imageUrl: "https://images.unsplash.com/photo-1535127022272-dbe7ee35cf33?w=400&q=80",
      },
      {
        name: "Peppermint Essential Oil",
        slug: "peppermint-essential-oil",
        brand: "Plant Therapy",
        description: "Pure peppermint oil for energy, headache relief, and digestive comfort.",
        price: 9.99,
        category: "essential-oils",
        certifications: ["USDA Organic", "Non-GMO"],
        imageUrl: "https://images.unsplash.com/photo-1600618528240-fb9fc964b853?w=400&q=80",
      },
      {
        name: "Eucalyptus Essential Oil",
        slug: "eucalyptus-essential-oil",
        brand: "Plant Therapy",
        description: "Steam-distilled eucalyptus for respiratory support and mental clarity.",
        price: 9.99,
        category: "essential-oils",
        certifications: ["USDA Organic", "Non-GMO"],
        imageUrl: "https://images.unsplash.com/photo-1619451334792-150fd785ee74?w=400&q=80",
      },
      {
        name: "Chamomile Herbal Tea",
        slug: "chamomile-herbal-tea",
        brand: "Traditional Medicinals",
        description: "Organic chamomile flowers for relaxation, sleep, and digestive calm.",
        price: 7.99,
        category: "herbal-teas",
        certifications: ["USDA Organic", "Non-GMO", "Vegan", "Fair Trade"],
        imageUrl: "https://images.unsplash.com/photo-1563822249366-3efb23b8ae9c?w=400&q=80",
      },
      {
        name: "Echinacea Immune Tea",
        slug: "echinacea-immune-tea",
        brand: "Traditional Medicinals",
        description: "Elderberry and echinacea blend to support immune defense naturally.",
        price: 8.49,
        category: "herbal-teas",
        certifications: ["USDA Organic", "Non-GMO", "Vegan", "Fair Trade"],
        imageUrl: "https://images.unsplash.com/photo-1597481499750-3e6b22637536?w=400&q=80",
      },
      {
        name: "Maca Root Powder",
        slug: "maca-root-powder",
        brand: "Navitas Organics",
        description: "Peruvian maca for energy, stamina, and hormonal balance. Adds to smoothies.",
        price: 16.99,
        category: "nutrition",
        certifications: ["USDA Organic", "Non-GMO", "Vegan", "Gluten-free"],
        imageUrl: "https://images.unsplash.com/photo-1611171711912-e3f6b0da7b0f?w=400&q=80",
      },
      {
        name: "Spirulina Powder",
        slug: "spirulina-powder",
        brand: "Nutrex Hawaii",
        description: "Hawaiian spirulina packed with protein, B12, and antioxidants. Superfood.",
        price: 22.99,
        category: "nutrition",
        certifications: ["Non-GMO", "Vegan", "Third-party tested"],
        imageUrl: "https://images.unsplash.com/photo-1490885578174-acda8905c2c6?w=400&q=80",
      },
      {
        name: "Reishi Mushroom Extract",
        slug: "reishi-mushroom",
        brand: "Four Sigmatic",
        description: "Dual-extracted reishi for stress resilience, immunity, and restful sleep.",
        price: 32.00,
        category: "supplements",
        certifications: ["USDA Organic", "Non-GMO", "Vegan", "Gluten-free"],
        imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&q=80",
      },
      {
        name: "Zinc Bisglycinate 25mg",
        slug: "zinc-bisglycinate",
        brand: "Thorne Research",
        description: "Highly absorbable zinc for immune function, skin health, and wound healing.",
        price: 14.00,
        category: "supplements",
        certifications: ["Non-GMO", "GMP Certified", "Gluten-free"],
        imageUrl: "https://images.unsplash.com/photo-1550572017-edd951b55104?w=400&q=80",
      },
      {
        name: "Valerian Root 500mg",
        slug: "valerian-root",
        brand: "Nature's Way",
        description: "Clinically studied herb for sleep onset and reducing nighttime waking.",
        price: 11.99,
        category: "supplements",
        certifications: ["Non-GMO", "Vegan", "Gluten-free"],
        imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&q=80",
      },
      {
        name: "Apple Cider Vinegar Gummies",
        slug: "acv-gummies",
        brand: "Goli Nutrition",
        description: "ACV with the mother for digestion, blood sugar balance, and energy.",
        price: 19.00,
        category: "nutrition",
        certifications: ["Non-GMO", "Vegan", "Gluten-free"],
        imageUrl: "https://images.unsplash.com/photo-1559181567-c3190b2e6af9?w=400&q=80",
      },
      {
        name: "Frankincense Essential Oil",
        slug: "frankincense-essential-oil",
        brand: "Rocky Mountain Oils",
        description: "Sacred resin oil for inflammation, meditation, and skin rejuvenation.",
        price: 19.99,
        category: "essential-oils",
        certifications: ["Non-GMO", "Third-party tested"],
        imageUrl: "https://images.unsplash.com/photo-1528720208104-3d9bd03cc9d4?w=400&q=80",
      },
      {
        name: "Immune Defense Tea",
        slug: "immune-defense-tea",
        brand: "Yogi Tea",
        description: "Echinacea, elderberry, and ginger blend to fortify your immune system.",
        price: 6.99,
        category: "herbal-teas",
        certifications: ["USDA Organic", "Non-GMO", "Vegan"],
        imageUrl: "https://images.unsplash.com/photo-1597481499750-3e6b22637536?w=400&q=80",
      },
      {
        name: "Biotin 5000mcg",
        slug: "biotin-5000mcg",
        brand: "Sports Research",
        description: "High-potency biotin for hair growth, nail strength, and energy metabolism.",
        price: 15.95,
        category: "supplements",
        certifications: ["Non-GMO", "Vegan", "Gluten-free", "Third-party tested"],
        imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80",
      },
      {
        name: "Rosehip Seed Oil",
        slug: "rosehip-seed-oil",
        brand: "Trilogy",
        description: "Cold-pressed rosehip for brightening, anti-aging, and scar reduction.",
        price: 24.00,
        category: "skincare",
        certifications: ["USDA Organic", "Non-GMO", "Vegan"],
        imageUrl: "https://images.unsplash.com/photo-1619451334792-150fd785ee74?w=400&q=80",
      },
    ],
  });

  console.log("✅ 26 products seeded!");
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(() => db.$disconnect());