import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@prisma/client";

const connectionString = process.env.DATABASE_URL!;
const adapter = new PrismaPg({ connectionString });
const db = new PrismaClient({ adapter });

async function main() {
  await db.recipe.deleteMany();

  await db.recipe.createMany({
    data: [
      // ───── Original 8 (now with type tags) ─────
      {
        name: "Ashwagandha golden sleep latte",
        slug: "ashwagandha-golden-sleep-latte",
        description: "A warming bedtime latte blending ashwagandha, turmeric, and cinnamon with creamy oat milk. A cozy nightly ritual that actually works.",
        prepTime: 5,
        servings: 1,
        costPerServing: 1.20,
        difficulty: "Easy",
        type: "tea",
        goals: ["sleep", "stress"],
        ingredients: [
          { amount: "1 cup", name: "Oat milk (unsweetened)" },
          { amount: "1 tsp", name: "Ashwagandha powder" },
          { amount: "½ tsp", name: "Turmeric powder" },
          { amount: "¼ tsp", name: "Cinnamon" },
          { amount: "1 pinch", name: "Black pepper" },
          { amount: "1 tsp", name: "Raw honey or maple syrup" },
        ],
        steps: [
          { step: 1, title: "Warm the milk", instruction: "Pour oat milk into a small saucepan. Heat over medium-low until steaming but not boiling." },
          { step: 2, title: "Mix the spice blend", instruction: "In your mug, combine ashwagandha, turmeric, cinnamon, and black pepper. Add 2 tbsp warm milk and stir into a smooth paste." },
          { step: 3, title: "Froth and combine", instruction: "Pour remaining warm milk into the mug. Froth with a handheld frother for 20 seconds for a creamy texture." },
          { step: 4, title: "Sweeten and serve", instruction: "Stir in honey or maple syrup to taste. Dust with extra cinnamon on top. Drink 30-60 minutes before bed." },
        ],
      },
      {
        name: "Elderberry immune syrup",
        slug: "elderberry-immune-syrup",
        description: "A potent homemade elderberry syrup loaded with antioxidants and immune-boosting compounds. Makes a 2-week supply for the whole family.",
        prepTime: 45,
        servings: 30,
        costPerServing: 0.40,
        difficulty: "Intermediate",
        type: "syrup",
        goals: ["immune", "energy"],
        ingredients: [
          { amount: "1 cup", name: "Dried elderberries" },
          { amount: "3 cups", name: "Water" },
          { amount: "1 tbsp", name: "Fresh grated ginger" },
          { amount: "1 tsp", name: "Cinnamon powder" },
          { amount: "½ tsp", name: "Cloves" },
          { amount: "1 cup", name: "Raw honey (added after cooling)" },
        ],
        steps: [
          { step: 1, title: "Simmer the berries", instruction: "Combine elderberries, water, ginger, cinnamon, and cloves in a saucepan. Bring to a boil then reduce to a simmer." },
          { step: 2, title: "Reduce", instruction: "Simmer uncovered for 45 minutes until liquid is reduced by almost half. The mixture will darken and thicken." },
          { step: 3, title: "Strain", instruction: "Remove from heat and let cool slightly. Pour through a fine mesh strainer, pressing berries to extract all liquid." },
          { step: 4, title: "Add honey", instruction: "Once cooled to room temperature, stir in raw honey. Never add honey to hot liquid — heat destroys its beneficial enzymes." },
          { step: 5, title: "Store", instruction: "Pour into a glass jar and refrigerate. Takes 1 tbsp daily for immune maintenance or 1 tbsp every 2-3 hours when sick." },
        ],
      },
      {
        name: "Turmeric golden milk paste",
        slug: "turmeric-golden-milk-paste",
        description: "A concentrated paste you make once and use all month. Just mix a teaspoon into warm milk each morning for powerful anti-inflammatory benefits.",
        prepTime: 15,
        servings: 30,
        costPerServing: 0.25,
        difficulty: "Easy",
        type: "paste",
        goals: ["gut", "joints", "immune"],
        ingredients: [
          { amount: "½ cup", name: "Turmeric powder" },
          { amount: "1 tsp", name: "Black pepper (boosts absorption 2000%)" },
          { amount: "½ tsp", name: "Ginger powder" },
          { amount: "½ tsp", name: "Cinnamon" },
          { amount: "¼ cup", name: "Coconut oil" },
          { amount: "⅓ cup", name: "Water" },
        ],
        steps: [
          { step: 1, title: "Combine dry ingredients", instruction: "Mix turmeric, black pepper, ginger, and cinnamon together in a small saucepan." },
          { step: 2, title: "Add water", instruction: "Add water and stir over medium-low heat for 5-7 minutes until a thick paste forms." },
          { step: 3, title: "Add coconut oil", instruction: "Remove from heat and stir in coconut oil until fully combined. The fat helps absorption of curcumin." },
          { step: 4, title: "Store and use", instruction: "Cool completely then store in a glass jar in the fridge for up to 30 days. Use 1 tsp per serving mixed into warm milk or smoothies." },
        ],
      },
      {
        name: "Chamomile honey sleep tea",
        slug: "chamomile-honey-sleep-tea",
        description: "The simplest, most effective bedtime tea. Just three ingredients and five minutes for a deeply calming pre-sleep ritual.",
        prepTime: 5,
        servings: 1,
        costPerServing: 0.80,
        difficulty: "Easy",
        type: "tea",
        goals: ["sleep", "stress"],
        ingredients: [
          { amount: "1 bag", name: "Chamomile tea (or 2 tsp loose leaf)" },
          { amount: "8 oz", name: "Hot water (not boiling — 200°F)" },
          { amount: "1 tsp", name: "Raw honey" },
          { amount: "1 slice", name: "Fresh lemon (optional)" },
        ],
        steps: [
          { step: 1, title: "Heat water", instruction: "Heat water to 200°F — just before boiling. Boiling water can make chamomile bitter and destroy delicate compounds." },
          { step: 2, title: "Steep", instruction: "Add chamomile tea bag or loose leaf to your mug. Pour hot water over it and steep for 5 minutes covered with a small plate to trap the steam." },
          { step: 3, title: "Sweeten", instruction: "Remove the tea bag. Add honey and stir gently. Add lemon if using. Sip slowly 30 minutes before bed." },
        ],
      },
      {
        name: "Peppermint focus tea",
        slug: "peppermint-focus-tea",
        description: "A caffeine-free alternative to coffee that sharpens mental clarity and lifts energy through peppermint's natural stimulating compounds.",
        prepTime: 5,
        servings: 1,
        costPerServing: 0.60,
        difficulty: "Easy",
        type: "tea",
        goals: ["energy", "focus", "stress"],
        ingredients: [
          { amount: "1 tbsp", name: "Fresh or dried peppermint leaves" },
          { amount: "8 oz", name: "Hot water" },
          { amount: "1 tsp", name: "Honey (optional)" },
          { amount: "2 drops", name: "Peppermint essential oil (food-grade, optional)" },
        ],
        steps: [
          { step: 1, title: "Prepare leaves", instruction: "If using fresh peppermint, bruise the leaves slightly by rubbing between your palms to release the oils." },
          { step: 2, title: "Steep", instruction: "Place leaves in a mug or infuser. Pour hot water over and steep for 3-5 minutes. Longer steeping = stronger flavor." },
          { step: 3, title: "Serve", instruction: "Strain if needed. Add honey if desired. Inhale the steam before drinking — the aroma alone boosts alertness." },
        ],
      },
      {
        name: "Ginger lemon immune shot",
        slug: "ginger-lemon-immune-shot",
        description: "A powerful 2oz shot of concentrated ginger, lemon, and turmeric. Take it every morning to prime your immune system for the day.",
        prepTime: 10,
        servings: 6,
        costPerServing: 0.50,
        difficulty: "Easy",
        type: "tonic",
        goals: ["immune", "energy", "gut"],
        ingredients: [
          { amount: "4 inches", name: "Fresh ginger root, peeled" },
          { amount: "3", name: "Lemons, juiced" },
          { amount: "1 tsp", name: "Turmeric powder" },
          { amount: "1 pinch", name: "Cayenne pepper" },
          { amount: "1 tbsp", name: "Raw honey" },
          { amount: "½ cup", name: "Water" },
        ],
        steps: [
          { step: 1, title: "Juice the ginger", instruction: "Blend ginger with water then strain through a fine mesh strainer, pressing to extract all the juice." },
          { step: 2, title: "Combine", instruction: "Mix ginger juice, lemon juice, turmeric, cayenne, and honey in a jar. Stir or shake well." },
          { step: 3, title: "Store", instruction: "Refrigerate in a sealed glass jar for up to 5 days. Shake before each use. Take 2oz shot each morning on an empty stomach." },
        ],
      },
      {
        name: "Lavender oat milk bath soak",
        slug: "lavender-oat-bath-soak",
        description: "A luxurious DIY bath soak that calms the nervous system, softens skin, and prepares your body for deep sleep. Make a big batch and store it.",
        prepTime: 10,
        servings: 8,
        costPerServing: 0.90,
        difficulty: "Easy",
        type: "bath-soak",
        goals: ["sleep", "stress", "skin"],
        ingredients: [
          { amount: "2 cups", name: "Colloidal oats (finely ground rolled oats)" },
          { amount: "1 cup", name: "Epsom salt" },
          { amount: "½ cup", name: "Baking soda" },
          { amount: "20 drops", name: "Lavender essential oil" },
          { amount: "10 drops", name: "Chamomile essential oil (optional)" },
        ],
        steps: [
          { step: 1, title: "Grind oats", instruction: "If you don't have colloidal oats, blend regular rolled oats in a blender until a fine powder forms. They should dissolve in water." },
          { step: 2, title: "Mix dry ingredients", instruction: "Combine oats, epsom salt, and baking soda in a large bowl. Stir well." },
          { step: 3, title: "Add essential oils", instruction: "Drizzle lavender and chamomile oils over the mixture. Stir thoroughly to distribute evenly." },
          { step: 4, title: "Store and use", instruction: "Store in a sealed glass jar. Add ¼ cup to warm bath water. Soak for 20 minutes before bed for best sleep results." },
        ],
      },
      {
        name: "Maca energy smoothie",
        slug: "maca-energy-smoothie",
        description: "A nutrient-dense morning smoothie with maca root, banana, and almond butter for sustained energy without the coffee crash.",
        prepTime: 5,
        servings: 1,
        costPerServing: 2.50,
        difficulty: "Easy",
        type: "smoothie",
        goals: ["energy", "hormones"],
        ingredients: [
          { amount: "1 tsp", name: "Maca root powder" },
          { amount: "1", name: "Frozen banana" },
          { amount: "1 tbsp", name: "Almond butter" },
          { amount: "1 cup", name: "Oat milk or almond milk" },
          { amount: "1 tsp", name: "Cacao powder" },
          { amount: "1 tsp", name: "Honey" },
          { amount: "1 cup", name: "Ice" },
        ],
        steps: [
          { step: 1, title: "Add all ingredients", instruction: "Place all ingredients in a blender. Start with the liquid at the bottom to help blending." },
          { step: 2, title: "Blend", instruction: "Blend on high for 45-60 seconds until completely smooth and creamy." },
          { step: 3, title: "Serve immediately", instruction: "Pour into a glass and drink right away. Maca works best consumed in the morning — avoid taking after 2pm as it can interfere with sleep." },
        ],
      },

      // ───── 12 new recipes spanning the expanded categories ─────
      {
        name: "Calendula healing salve",
        slug: "calendula-healing-salve",
        description: "A gentle, skin-soothing balm for cuts, bug bites, and dry patches. Calendula-infused oil plus beeswax produces a kid-safe salve that lasts a year.",
        prepTime: 60,
        servings: 4,
        costPerServing: 3.50,
        difficulty: "Intermediate",
        type: "balm",
        goals: ["skin", "kids"],
        ingredients: [
          { amount: "1 cup", name: "Dried calendula flowers" },
          { amount: "1 cup", name: "Olive or jojoba oil" },
          { amount: "1 oz", name: "Beeswax pellets" },
          { amount: "10 drops", name: "Lavender essential oil (optional)" },
          { amount: "4", name: "Small glass tins (1 oz each)" },
        ],
        steps: [
          { step: 1, title: "Infuse the oil", instruction: "Combine calendula and oil in a glass jar. Place in a double boiler over low heat for 1 hour, or sit in a sunny window for 4-6 weeks for a slower infusion." },
          { step: 2, title: "Strain", instruction: "Pour through a fine mesh strainer lined with cheesecloth, pressing the flowers to extract all the oil. Discard the spent flowers." },
          { step: 3, title: "Melt the beeswax", instruction: "Return the strained oil to the double boiler. Add beeswax and stir until fully melted and combined." },
          { step: 4, title: "Pour and cool", instruction: "Remove from heat. Stir in lavender oil if using. Pour into tins and let set for 1 hour. Apply 1-2 times daily to affected skin. Shelf life: 1 year." },
        ],
      },
      {
        name: "Honey lavender lip balm",
        slug: "honey-lavender-lip-balm",
        description: "A simple three-ingredient lip balm with the sweetness of raw honey and a hint of lavender. Smooths chapped lips overnight.",
        prepTime: 20,
        servings: 6,
        costPerServing: 1.20,
        difficulty: "Easy",
        type: "balm",
        goals: ["skin", "beauty"],
        ingredients: [
          { amount: "2 tbsp", name: "Coconut oil" },
          { amount: "1 tbsp", name: "Beeswax pellets" },
          { amount: "1 tsp", name: "Raw honey" },
          { amount: "5 drops", name: "Lavender essential oil" },
          { amount: "6", name: "Empty lip balm tubes or small tins" },
        ],
        steps: [
          { step: 1, title: "Melt", instruction: "Combine coconut oil and beeswax in a double boiler. Stir until fully melted and clear, about 5 minutes." },
          { step: 2, title: "Add honey and oil", instruction: "Remove from heat. Add raw honey and lavender oil. Stir vigorously for 30 seconds — honey doesn't fully blend, but it'll suspend in the wax as it sets." },
          { step: 3, title: "Pour", instruction: "Working quickly before it hardens, pour into lip balm tubes or tins. Tap gently to remove air bubbles." },
          { step: 4, title: "Set", instruction: "Let cool at room temperature for 30 minutes until firm. Cap and label. Use within 6 months." },
        ],
      },
      {
        name: "Echinacea immune tincture",
        slug: "echinacea-immune-tincture",
        description: "A traditional alcohol-extracted echinacea tincture you take by the dropperful at the first sign of a cold. Makes a 6-month supply.",
        prepTime: 15,
        servings: 60,
        costPerServing: 0.30,
        difficulty: "Easy",
        type: "tincture",
        goals: ["immune"],
        ingredients: [
          { amount: "1 cup", name: "Dried echinacea root (or fresh, finely chopped)" },
          { amount: "2 cups", name: "Vodka (80 proof or higher)" },
          { amount: "1", name: "Pint-size mason jar with lid" },
          { amount: "1", name: "Amber dropper bottle for storage" },
        ],
        steps: [
          { step: 1, title: "Fill the jar", instruction: "Place echinacea in the mason jar — fill about ⅔ full with dried root, or completely full if using fresh." },
          { step: 2, title: "Cover with vodka", instruction: "Pour vodka over the root until it's fully submerged with at least 2 inches of liquid above the plant material." },
          { step: 3, title: "Steep", instruction: "Seal tightly. Store in a cool, dark cabinet for 4-6 weeks, shaking the jar every 2-3 days. The liquid will turn deep amber." },
          { step: 4, title: "Strain and bottle", instruction: "Strain through cheesecloth, squeezing to extract all liquid. Transfer to amber dropper bottles. Take 1 dropperful (about 30 drops) up to 3 times daily at the onset of illness." },
        ],
      },
      {
        name: "Lemon balm calming tincture",
        slug: "lemon-balm-calming-tincture",
        description: "A gentle, mood-lifting tincture from lemon balm leaf. Helps with anxious moments, racing thoughts, and falling asleep without sedation.",
        prepTime: 15,
        servings: 60,
        costPerServing: 0.25,
        difficulty: "Easy",
        type: "tincture",
        goals: ["stress", "mood", "sleep"],
        ingredients: [
          { amount: "1 cup", name: "Dried lemon balm leaf" },
          { amount: "2 cups", name: "Vodka (80 proof or higher)" },
          { amount: "1", name: "Pint-size mason jar with lid" },
          { amount: "1", name: "Amber dropper bottle for storage" },
        ],
        steps: [
          { step: 1, title: "Fill the jar", instruction: "Loosely fill the mason jar ⅔ full with dried lemon balm. Don't pack it down — the leaves need room to circulate." },
          { step: 2, title: "Cover with vodka", instruction: "Pour vodka over the leaves until fully covered with 2 inches of liquid on top. Seal tightly." },
          { step: 3, title: "Steep", instruction: "Store in a dark cabinet for 4-6 weeks, shaking every few days. The liquid will become a soft golden-green." },
          { step: 4, title: "Strain and use", instruction: "Strain through cheesecloth into a dropper bottle. Take ½ to 1 dropperful as needed for stress, or 30 minutes before bed for sleep." },
        ],
      },
      {
        name: "Rosemary peppermint focus roller",
        slug: "rosemary-peppermint-focus-roller",
        description: "A diluted essential oil roller for your wrists and temples. Rosemary and peppermint together are clinically shown to improve memory and alertness.",
        prepTime: 5,
        servings: 1,
        costPerServing: 4.00,
        difficulty: "Easy",
        type: "oil-blend",
        goals: ["focus", "energy"],
        ingredients: [
          { amount: "10 drops", name: "Rosemary essential oil" },
          { amount: "8 drops", name: "Peppermint essential oil" },
          { amount: "5 drops", name: "Lemon essential oil" },
          { amount: "10 ml", name: "Fractionated coconut oil (carrier)" },
          { amount: "1", name: "10 ml glass roller bottle" },
        ],
        steps: [
          { step: 1, title: "Add essential oils", instruction: "Drop rosemary, peppermint, and lemon oils directly into the empty roller bottle." },
          { step: 2, title: "Top with carrier oil", instruction: "Fill the rest of the bottle with fractionated coconut oil, leaving a small space at the top for the rollerball." },
          { step: 3, title: "Cap and shake", instruction: "Snap the rollerball cap on. Shake gently for 10 seconds to combine. Always shake before each use." },
          { step: 4, title: "Use", instruction: "Roll on inner wrists, temples, and back of neck before deep work or studying. Avoid eyes. Reapply every 2-3 hours as needed." },
        ],
      },
      {
        name: "Lavender bergamot stress roller",
        slug: "lavender-bergamot-stress-roller",
        description: "A pocket-sized de-stress tool. Lavender + bergamot is the classic anxiety blend — citrusy and calming at the same time.",
        prepTime: 5,
        servings: 1,
        costPerServing: 4.50,
        difficulty: "Easy",
        type: "oil-blend",
        goals: ["stress", "mood"],
        ingredients: [
          { amount: "12 drops", name: "Lavender essential oil" },
          { amount: "8 drops", name: "Bergamot essential oil" },
          { amount: "4 drops", name: "Frankincense essential oil (optional)" },
          { amount: "10 ml", name: "Fractionated coconut oil" },
          { amount: "1", name: "10 ml glass roller bottle" },
        ],
        steps: [
          { step: 1, title: "Combine oils", instruction: "Add lavender, bergamot, and frankincense (if using) to the empty roller bottle." },
          { step: 2, title: "Add carrier", instruction: "Fill to the neck with fractionated coconut oil. Cap and shake to mix." },
          { step: 3, title: "Use", instruction: "Roll on wrists and behind ears whenever you feel tension building. Inhale deeply 3-4 times. Bergamot is photosensitive — avoid direct sun on application sites for 12 hours." },
        ],
      },
      {
        name: "Hibiscus rose beauty tea",
        slug: "hibiscus-rose-beauty-tea",
        description: "A vibrant ruby-colored tea rich in vitamin C and antioxidants. Drink daily for collagen support and a natural skin glow.",
        prepTime: 8,
        servings: 1,
        costPerServing: 0.55,
        difficulty: "Easy",
        type: "tea",
        goals: ["beauty", "skin"],
        ingredients: [
          { amount: "1 tbsp", name: "Dried hibiscus flowers" },
          { amount: "1 tsp", name: "Dried rose petals" },
          { amount: "1 tsp", name: "Dried rosehips" },
          { amount: "8 oz", name: "Hot water (just off boil)" },
          { amount: "1 tsp", name: "Raw honey (optional)" },
        ],
        steps: [
          { step: 1, title: "Combine herbs", instruction: "Add hibiscus, rose petals, and rosehips to a tea infuser or directly into your mug." },
          { step: 2, title: "Steep", instruction: "Pour hot water over the herbs and cover with a small plate. Steep for 6-8 minutes — longer steeping deepens the color and flavor." },
          { step: 3, title: "Strain and sweeten", instruction: "Strain into your mug. Add honey if desired. Drink iced in summer or hot in winter. Enjoy daily for visible benefits in 4-6 weeks." },
        ],
      },
      {
        name: "Dandelion root detox tea",
        slug: "dandelion-root-detox-tea",
        description: "A coffee-like tea brewed from roasted dandelion root. Traditionally used to support liver function and gentle daily detoxification.",
        prepTime: 12,
        servings: 1,
        costPerServing: 0.45,
        difficulty: "Easy",
        type: "tea",
        goals: ["detox", "gut"],
        ingredients: [
          { amount: "1 tbsp", name: "Roasted dandelion root (granular)" },
          { amount: "10 oz", name: "Water" },
          { amount: "1 cinnamon stick", name: "Cinnamon (optional)" },
          { amount: "Splash", name: "Oat milk (optional)" },
        ],
        steps: [
          { step: 1, title: "Decoct the root", instruction: "Roots need a longer extraction than leaves. Combine dandelion root, water, and cinnamon in a small saucepan. Bring to a boil." },
          { step: 2, title: "Simmer", instruction: "Reduce heat and simmer covered for 10 minutes. The water will turn deep brown and smell pleasantly toasted." },
          { step: 3, title: "Strain and serve", instruction: "Strain into a mug. Add a splash of oat milk for a coffee-like drink. Enjoy in the morning as a daily liver tonic." },
        ],
      },
      {
        name: "Sea moss gel",
        slug: "sea-moss-gel",
        description: "A mineral-rich gel base you stir into smoothies, oatmeal, or skincare. Sea moss contains 92 of the 102 minerals our bodies need.",
        prepTime: 30,
        servings: 30,
        costPerServing: 0.65,
        difficulty: "Intermediate",
        type: "paste",
        goals: ["gut", "beauty", "skin"],
        ingredients: [
          { amount: "2 oz", name: "Dried raw sea moss" },
          { amount: "2 cups", name: "Spring or filtered water (for soaking)" },
          { amount: "1 cup", name: "Fresh spring water (for blending)" },
          { amount: "1", name: "Lime, juiced (preserves freshness)" },
        ],
        steps: [
          { step: 1, title: "Rinse thoroughly", instruction: "Rinse dried sea moss under cool running water until the water runs clear. This removes salt and any debris." },
          { step: 2, title: "Soak", instruction: "Submerge in 2 cups of spring water with the lime juice. Cover and refrigerate for 12-24 hours. The moss will expand 3-4x in size and turn pale." },
          { step: 3, title: "Blend", instruction: "Drain and rinse the soaked moss. Add to a blender with 1 cup fresh spring water. Blend on high for 1-2 minutes until completely smooth." },
          { step: 4, title: "Store", instruction: "Pour into a glass jar and refrigerate. Take 1-2 tbsp daily in smoothies, oatmeal, or applied as a face mask. Lasts 3-4 weeks refrigerated." },
        ],
      },
      {
        name: "Cacao maca focus smoothie",
        slug: "cacao-maca-focus-smoothie",
        description: "A rich chocolate-flavored smoothie that lifts mood, sharpens focus, and supports steady energy through cacao's natural compounds.",
        prepTime: 5,
        servings: 1,
        costPerServing: 2.80,
        difficulty: "Easy",
        type: "smoothie",
        goals: ["focus", "mood", "energy"],
        ingredients: [
          { amount: "1 tbsp", name: "Raw cacao powder" },
          { amount: "1 tsp", name: "Maca root powder" },
          { amount: "1", name: "Frozen banana" },
          { amount: "2 tbsp", name: "Almond butter" },
          { amount: "1 cup", name: "Oat milk" },
          { amount: "1 medjool date", name: "Medjool date (pitted)" },
          { amount: "½ cup", name: "Ice" },
        ],
        steps: [
          { step: 1, title: "Layer ingredients", instruction: "Add oat milk first, then date and frozen banana, then powders and almond butter. Top with ice." },
          { step: 2, title: "Blend", instruction: "Blend on high for 60 seconds until completely smooth and frothy. The texture should be like a milkshake." },
          { step: 3, title: "Serve", instruction: "Pour into a glass and drink within 10 minutes for best texture. Best consumed before noon — both cacao and maca can be too stimulating later in the day." },
        ],
      },
      {
        name: "Honey ginger kids' cough syrup",
        slug: "honey-ginger-kids-cough-syrup",
        description: "A gentle, alcohol-free syrup that calms coughs and soothes sore throats. Safe for kids over 1 year (honey is the only adult-only restriction).",
        prepTime: 25,
        servings: 24,
        costPerServing: 0.35,
        difficulty: "Easy",
        type: "syrup",
        goals: ["immune", "kids"],
        ingredients: [
          { amount: "2 inches", name: "Fresh ginger root, sliced thin" },
          { amount: "1 lemon", name: "Lemon, sliced" },
          { amount: "2 cups", name: "Water" },
          { amount: "1 tsp", name: "Whole cloves" },
          { amount: "1 cinnamon stick", name: "Cinnamon" },
          { amount: "1 cup", name: "Raw local honey (added after cooling)" },
        ],
        steps: [
          { step: 1, title: "Simmer aromatics", instruction: "Combine ginger, lemon, water, cloves, and cinnamon in a small saucepan. Bring to a boil then reduce to a low simmer." },
          { step: 2, title: "Reduce", instruction: "Simmer uncovered for 20 minutes until liquid reduces by half. The mixture will smell warm and spicy." },
          { step: 3, title: "Strain and cool", instruction: "Strain into a measuring cup, pressing solids to extract all liquid. Discard solids. Let cool to lukewarm — never add honey to hot liquid." },
          { step: 4, title: "Add honey", instruction: "Stir in raw honey until fully dissolved. Pour into a glass bottle. Refrigerate up to 2 months. Give 1 tsp to kids ages 1+ as needed; 1 tbsp for adults. Not for babies under 1 year." },
        ],
      },
      {
        name: "Magnesium epsom foot soak",
        slug: "magnesium-epsom-foot-soak",
        description: "A 20-minute foot soak that loads your body with magnesium through the skin. Eases sore muscles, calms the mind, and helps you fall asleep faster.",
        prepTime: 5,
        servings: 6,
        costPerServing: 0.75,
        difficulty: "Easy",
        type: "bath-soak",
        goals: ["sleep", "joints"],
        ingredients: [
          { amount: "3 cups", name: "Epsom salt (magnesium sulfate)" },
          { amount: "1 cup", name: "Coarse sea salt" },
          { amount: "½ cup", name: "Baking soda" },
          { amount: "20 drops", name: "Lavender essential oil" },
          { amount: "10 drops", name: "Eucalyptus essential oil" },
        ],
        steps: [
          { step: 1, title: "Mix the dry blend", instruction: "Combine epsom salt, sea salt, and baking soda in a large bowl. Stir thoroughly to evenly distribute." },
          { step: 2, title: "Add essential oils", instruction: "Drizzle lavender and eucalyptus oils over the salt mixture. Stir for 1 minute to fully incorporate. Store in a glass jar." },
          { step: 3, title: "Soak", instruction: "Add ½ cup of the blend to a tub or basin filled with hot water deep enough to cover your ankles. Soak 20 minutes, ideally 1 hour before bed." },
          { step: 4, title: "Finish", instruction: "Pat feet dry — don't rinse, so the magnesium continues absorbing. Follow with a body lotion if your skin is dry." },
        ],
      },
    ],
  });

  console.log("✅ 20 recipes seeded across 9 types and 13 goals!");
}

main()
  .catch((e) => {
    console.error("❌ Recipe seed failed:", e);
    process.exit(1);
  })
  .finally(() => db.$disconnect());
